version: "3"
services:
  db:
    image: mysql:8
    container_name: api_db
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_TCP_PORT: 3307
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      dev:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api_pma
    ports:
      - "8081:80"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: api_www
    ports:
      - "8080:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
